//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.05 at 04:34:22 PM IST 
//


package com.example.soap_api_practice.dtos.generatedService1Dtos;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://example.com/order}getOrdersResponse"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getOrdersResponse"
})
@XmlRootElement(name = "Body", namespace = "http://schemas.xmlsoap.org/soap/envelope/")
public class Body {

    @XmlElement(required = true)
    protected GetOrdersResponse getOrdersResponse;

    /**
     * Gets the value of the getOrdersResponse property.
     * 
     * @return
     *     possible object is
     *     {@link GetOrdersResponse }
     *     
     */
    public GetOrdersResponse getGetOrdersResponse() {
        return getOrdersResponse;
    }

    /**
     * Sets the value of the getOrdersResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetOrdersResponse }
     *     
     */
    public void setGetOrdersResponse(GetOrdersResponse value) {
        this.getOrdersResponse = value;
    }

}
